# Generated by Django 5.2.6 on 2025-09-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Nanay', max_length=150)),
                ('body', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('map_link', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Contact info',
            },
        ),
        migrations.AlterField(
            model_name='kakanin',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kakanin',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
