# Generated by Django 5.2.6 on 2025-09-07 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0002_aboutpage_contactinfo_alter_kakanin_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kakanin',
            name='description',
        ),
        migrations.RemoveField(
            model_name='kakanin',
            name='image',
        ),
        migrations.AlterField(
            model_name='kakanin',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kakanin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakanin.kakanin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kakanin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakanin.kakanin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
