# Generated by Django 5.2.6 on 2025-09-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0004_kakanin_description_kakanin_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kakanin',
            name='description',
        ),
        migrations.RemoveField(
            model_name='kakanin',
            name='image',
        ),
        migrations.AlterField(
            model_name='kakanin',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
