# Generated by Django 5.2.6 on 2025-09-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0005_remove_kakanin_description_remove_kakanin_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakanin',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kakanin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kakanin_images/'),
        ),
    ]
