# Generated by Django 5.2.6 on 2025-09-14 19:24

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0008_order_delivery_address_order_delivery_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # UserProfile already exists in migration 0008, so this migration is empty
    ]
