# Generated by Django 5.2.6 on 2025-09-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0009_auto_20250915_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakanin',
            name='available_days',
            field=models.JSONField(blank=True, default=list, help_text='Days of the week when available'),
        ),
        migrations.AddField(
            model_name='kakanin',
            name='available_from_time',
            field=models.TimeField(blank=True, help_text='Available from this time', null=True),
        ),
        migrations.AddField(
            model_name='kakanin',
            name='available_to_time',
            field=models.TimeField(blank=True, help_text='Available until this time', null=True),
        ),
        migrations.AddField(
            model_name='kakanin',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Is this product currently available?'),
        ),
        migrations.AddField(
            model_name='kakanin',
            name='max_daily_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum quantity available per day', null=True),
        ),
        migrations.AddField(
            model_name='kakanin',
            name='preparation_time_hours',
            field=models.PositiveIntegerField(default=0, help_text='Hours needed to prepare this item'),
        ),
    ]
