# Generated by Django 5.2.6 on 2025-09-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0010_kakanin_available_days_kakanin_available_from_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakanin',
            name='category',
            field=models.CharField(choices=[('rice', 'Rice-based'), ('coconut', 'Coconut'), ('sweet', 'Sweet'), ('traditional', 'Traditional'), ('modern', 'Modern')], default='rice', help_text='Category of kakanin', max_length=20),
        ),
    ]
