# Generated by Django 5.2.6 on 2025-09-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0011_kakanin_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kakanin',
            name='category',
        ),
        migrations.AddField(
            model_name='kakanin',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text='Categories of kakanin (can select multiple)'),
        ),
    ]
