# Generated by Django 5.2.6 on 2025-10-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0012_remove_kakanin_category_kakanin_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
