# Generated by Django 5.2.6 on 2025-10-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0016_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
        migrations.AddField(
            model_name='feedback',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='decision_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
