# Generated by Django 4.2.25 on 2025-10-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0018_remove_feedback_decided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='bundles',
            field=models.ManyToManyField(blank=True, related_name='reservation_bundles', to='kakanin.kakanin'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='downpayment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='reservation',
            name='downpayment_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('gcash', 'GCash'), ('bank_transfer', 'Bank Transfer')], max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
