# Generated by Django 4.2.25 on 2025-10-12 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0019_reservation_bundles_reservation_downpayment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='kakanin.order'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_confirmation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_confirmation_type',
            field=models.CharField(blank=True, choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('unpaid', 'Unpaid')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('gcash', 'GCash'), ('bank_transfer', 'Bank Transfer'), ('cod', 'Cash on Delivery'), ('pickup_payment', 'Pickup Payment')], max_length=20),
        ),
    ]
