# Generated by Django 4.2.25 on 2025-10-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0020_reservation_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakanin',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Available pieces in stock'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
