# Generated by Django 4.2.25 on 2025-10-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0021_kakanin_stock_order_delivery_time_order_pickup_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_reservation', 'New Reservation'), ('payment_received', 'Payment Received'), ('low_stock', 'Low Stock')], max_length=32)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
