# Generated by Django 4.2.25 on 2025-10-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0023_reservation_expiry_at_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_reservation', 'New Reservation'), ('payment_received', 'Payment Received'), ('low_stock', 'Low Stock'), ('reservation_expired', 'Reservation Expired'), ('reservation_rejected', 'Reservation Rejected')], max_length=32),
        ),
    ]
