# Generated by Django 4.2.25 on 2025-10-12 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kakanin', '0024_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreorderCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='kakanin',
            name='allow_order_now',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kakanin',
            name='allow_reservation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kakanin',
            name='delivery_min_quantity',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='kakanin',
            name='min_order_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='kakanin',
            name='preorder_downpayment_percent',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='kakanin',
            name='reservation_downpayment_percent',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kakanin.reservationcart')),
                ('kakanin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakanin.kakanin')),
            ],
        ),
        migrations.CreateModel(
            name='PreorderCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kakanin.preordercart')),
                ('kakanin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakanin.kakanin')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_full', 'Order Full Payment'), ('preorder_dp', 'Preorder Downpayment'), ('reservation_dp', 'Reservation Downpayment')], max_length=20)),
                ('method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('gcash', 'GCash'), ('bank_transfer', 'Bank Transfer'), ('pickup_payment', 'Pickup Payment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
