# Generated by Django 4.2.25 on 2025-10-13 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0025_preordercart_reservationcart_kakanin_allow_order_now_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('downpayment_percent', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kakanin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_events', to='kakanin.kakanin')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='kakanin.reservationevent'),
        ),
    ]
