# Generated by Django 4.2.25 on 2025-10-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0026_reservationevent_reservation_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='kakanin',
        ),
        migrations.RemoveField(
            model_name='order',
            name='kakanin',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='preordercart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='preordercartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='preordercartitem',
            name='kakanin',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='bundles',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='event',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='kakanin',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='order',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reservationcart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reservationevent',
            name='kakanin',
        ),
        migrations.RemoveField(
            model_name='reservationitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='reservationitem',
            name='kakanin',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('low_stock', 'Low Stock')], max_length=32),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PreorderCart',
        ),
        migrations.DeleteModel(
            name='PreorderCartItem',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='ReservationCart',
        ),
        migrations.DeleteModel(
            name='ReservationEvent',
        ),
        migrations.DeleteModel(
            name='ReservationItem',
        ),
    ]
