# Generated by Django 4.2.25 on 2025-10-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0030_reservationcart_reservationcartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='delivery',
            field=models.BooleanField(default=False, help_text='True for delivery, False for pickup'),
        ),
    ]
