# Generated by Django 4.2.25 on 2025-10-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0031_reservation_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakanin',
            name='preparation_days',
            field=models.PositiveIntegerField(default=3, help_text='Days needed to prepare this item (e.g., 2, 3, 5 days)'),
        ),
    ]
