# Generated by Django 4.2.25 on 2025-10-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0032_kakanin_preparation_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address_notes',
            field=models.TextField(blank=True, help_text='Additional address details or delivery instructions'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='barangay',
            field=models.CharField(blank=True, help_text='Barangay', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='landmark',
            field=models.CharField(blank=True, help_text='Nearest landmark or establishment', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='municipality',
            field=models.CharField(blank=True, help_text='Municipality/City', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zone',
            field=models.CharField(blank=True, help_text='Zone/Purok/Street', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Full address (auto-generated from fields above)'),
        ),
    ]
