# Generated by Django 4.2.25 on 2025-10-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0033_userprofile_address_notes_userprofile_barangay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address_notes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='municipality',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Nearest landmark or additional directions'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='barangay',
            field=models.CharField(blank=True, choices=[('agpangi', 'Agpangi'), ('anislagan', 'Anislagan'), ('atipolo', 'Atipolo'), ('borac', 'Borac'), ('cabungaan', 'Cabungaan'), ('calumpang', 'Calumpang'), ('capiñahan', 'Capiñahan'), ('caraycaray', 'Caraycaray'), ('catmon', 'Catmon'), ('haguikhikan', 'Haguikhikan'), ('imelda', 'Imelda'), ('larrazabal', 'Larrazabal'), ('libtong', 'Libtong'), ('libertad', 'Libertad'), ('lico', 'Lico'), ('lucsoon', 'Lucsoon'), ('mabini', 'Mabini'), ('padre_inocentes_garcia', 'Padre Inocentes Garcia (Pob.)'), ('padre_sergio_eamiguel', 'Padre Sergio Eamiguel'), ('sabang', 'Sabang'), ('san_pablo', 'San Pablo'), ('santo_nino', 'Santo Niño'), ('santissimo_rosario', 'Santissimo Rosario Pob. (Santo Rosa)'), ('talustusan', 'Talustusan'), ('villa_caneja', 'Villa Caneja'), ('villa_consuelo', 'Villa Consuelo')], help_text='Barangay in Naval, Biliran', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zone',
            field=models.CharField(blank=True, help_text='Zone/Purok number', max_length=50),
        ),
    ]
