# Generated by Django 4.2.25 on 2025-11-01 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kakanin', '0034_remove_userprofile_address_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('low_stock', 'Low Stock'), ('order_submitted', 'Order Submitted'), ('payment_pending', 'Payment Pending'), ('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('order_confirmed', 'Order Confirmed'), ('ready_for_pickup', 'Ready for Pickup'), ('out_for_delivery', 'Out for Delivery'), ('order_completed', 'Order Completed'), ('order_cancelled', 'Order Cancelled'), ('reservation_submitted', 'Reservation Submitted'), ('reservation_confirmed', 'Reservation Confirmed'), ('reservation_rejected', 'Reservation Rejected'), ('reservation_completed', 'Reservation Completed'), ('feedback', 'Feedback Received')], max_length=32),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Product quality rating (1-5 stars)')),
                ('product_comment', models.TextField(blank=True, help_text='Comments about the product quality')),
                ('service_rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Service rating (1-5 stars)')),
                ('service_comment', models.TextField(blank=True, help_text='Comments about the service')),
                ('delivery_rating', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Delivery service rating (1-5 stars)', null=True)),
                ('delivery_comment', models.TextField(blank=True, help_text='Comments about delivery (timeliness, condition, etc.)')),
                ('pickup_speed_rating', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Pickup confirmation speed (1-5 stars)', null=True)),
                ('overall_comment', models.TextField(blank=True, help_text='Overall experience and suggestions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='kakanin.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
