# Generated by Django 4.2.25 on 2025-11-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0035_alter_notification_type_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image attachment', null=True, upload_to='message_images/'),
        ),
    ]
