# Generated by Django 4.2.25 on 2025-11-11 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0036_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='kakanin.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='unsent_for_everyone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='unsent_for_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='unsent_for_sender',
            field=models.BooleanField(default=False),
        ),
    ]
