# Generated by Django 4.2.25 on 2025-12-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakanin', '0039_contactinfo_remove_instagram_tiktok_add_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('low_stock', 'Low Stock'), ('order_submitted', 'Order Submitted'), ('payment_pending', 'Payment Pending'), ('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('order_confirmed', 'Order Confirmed'), ('ready_for_pickup', 'Ready for Pickup'), ('out_for_delivery', 'Out for Delivery'), ('order_completed', 'Order Completed'), ('order_cancelled', 'Order Cancelled'), ('reservation_submitted', 'Reservation Submitted'), ('reservation_pending_payment', 'Reservation Pending Payment'), ('reservation_confirmed', 'Reservation Confirmed'), ('reservation_rejected', 'Reservation Rejected'), ('reservation_completed', 'Reservation Completed'), ('feedback', 'Feedback Received')], max_length=32),
        ),
    ]
